import React from 'react';
import './shared.css';

const GPUClusteringDetails = () => {
    return (
        <div className="gpu-clustering-details">
            <section className="section" style={{ marginTop: '2em', paddingTop: '2em' }}>
                <h2 className="section-title">Overview</h2>
                <div className="project-blog" style={{ lineHeight: '1.8' }}>
                    <p style={{ marginBottom: '1.5em' }}>
                        Clustering large, dense point clouds generated by automotive sensors (radar/LiDAR) is highly compute-intensive. This project implements a parallelized DBSCAN algorithm in CUDA, achieving massive speedups by shifting the execution model from sequential BFS/DFS queue expansion to parallel disjoint set tree merges.
                    </p>
                    <p style={{ fontWeight: 'bold', marginBottom: '0.5em' }}>Key architectural pillars:</p>
                    <ol style={{ paddingLeft: '1.5em', marginBottom: '1.5em' }}>
                        <li style={{ marginBottom: '0.8em' }}>
                            <b>Sorted Spatial Grid</b>: Maps points into 3D grid cells of size epsilon. Points are sorted by cell hash using <code>thrust::sort_by_key</code>, replacing costly hash-maps or O(N²) checks with binary search queries.
                        </li>
                        <li style={{ marginBottom: '0.8em' }}>
                            <b>Lock-Free Parallel DSU</b>: Leverages <code>atomicCAS</code> (Compare-And-Swap) for thread-safe tree merges and grandparent-halving path compression, performing the entire clustering sequence directly on the GPU.
                        </li>
                        <li style={{ marginBottom: '0.8em' }}>
                            <b>Hardware Fallback Target</b>: Configured code structure with a CPU-only compilation target to enable development and validation on machines without physical NVIDIA hardware.
                        </li>
                    </ol>
                </div>
            </section>

            {/* Spatial Grid Section */}
            <div style={{ borderLeft: '4px solid var(--accent-primary)', paddingLeft: '1.5em', marginTop: '4em' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1em' }}>
                    <h2 style={{ fontSize: '1.8em', margin: 0 }}>1. Sorted Spatial Grid</h2>
                </div>
                <p style={{ color: 'var(--text-secondary)', fontStyle: 'italic', marginTop: '0.5em' }}>Linearizing Spatial Neighborhood Search</p>
            </div>

            <section className="section" style={{ marginTop: '2em' }}>
                <p style={{ lineHeight: '1.8' }}>
                    A naive DBSCAN algorithm calculates the Euclidean distance between every pair of points in the dataset. This results in quadratic complexity:
                </p>
                <div className="math-equation">
                    Time Complexity: O(N²) &nbsp;|&nbsp; Space Complexity: O(N²)
                </div>
                <p style={{ lineHeight: '1.8', marginTop: '1.5em' }}>
                    For dense point clouds (e.g., 100,000 points generated by a LiDAR or high-resolution radar scan), a distance matrix is completely infeasible as it would consume over 40 GB of GPU memory. To overcome this limitation, I implemented a <b>Sorted Spatial Grid</b>:
                </p>
                <ul className="bullet-points" style={{ marginTop: '1.5em', lineHeight: '1.8' }}>
                    <li><strong>3D Cell Hashing:</strong> Coordinates are mapped to discrete integer cell indices based on the search radius epsilon (ε). A point at coordinate (x, y, z) falls into cell (floor(x/ε), floor(y/ε), floor(z/ε)).</li>
                    <li><strong>GPU Parallel Sorting:</strong> The coordinates are sorted in VRAM using <code>thrust::sort_by_key</code> based on their cell hashes. This forces spatially neighboring points to be laid out contiguously in memory.</li>
                    <li><strong>Binary Search Lookup:</strong> Rather than constructing a complex GPU hash map, cell offsets (start/end indices) are identified in the sorted array, enabling threads to search neighbor cells in O(log N) or O(1) expected time.</li>
                </ul>
            </section>

            {/* DSU Section */}
            <div style={{ borderLeft: '4px solid var(--accent-secondary, #ff4d4d)', paddingLeft: '1.5em', marginTop: '5em' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1em' }}>
                    <h2 style={{ fontSize: '1.8em', margin: 0 }}>2. Lock-Free Parallel DSU</h2>
                </div>
                <p style={{ color: 'var(--text-secondary)', fontStyle: 'italic', marginTop: '0.5em' }}>Parallelizing Cluster Expansion via Union-Find</p>
            </div>

            <section className="section" style={{ marginTop: '2em' }}>
                <p style={{ lineHeight: '1.8' }}>
                    Standard DBSCAN expands clusters sequentially by starting from a core point and adding its neighbors to a queue (acting like Breadth-First or Depth-First Search). This sequential traversal is highly unsuited for execution on GPU architectures, which favor data parallelism over thread state tracking.
                </p>
                <p style={{ lineHeight: '1.8', marginTop: '1.5em' }}>
                    In this implementation, cluster traversal is completely bypassed by mapping the problem to a <strong>Disjoint Set Union (DSU) / Union-Find</strong> structure:
                </p>
                <ul className="bullet-points" style={{ marginTop: '1.5em', lineHeight: '1.8' }}>
                    <li><strong>Parallel Core Association:</strong> Every core point starts as its own independent cluster set. If two core points lie within epsilon distance of each other, they are merged.</li>
                    <li><strong>Lock-Free Atomic Merges:</strong> To resolve write contention when multiple GPU threads attempt to link overlapping clusters, tree roots are joined thread-safely using a Compare-And-Swap loop with <code>atomicCAS</code>.</li>
                    <li><strong>Grandparent Halving:</strong> During the root lookup phase, path compression is implemented to compress the parent-pointer trees on the fly, keeping maximum tree heights minimal and operations extremely fast.</li>
                </ul>
            </section>

            {/* Performance Benchmarks Section */}
            <div style={{ borderLeft: '4px solid #3BFF00', paddingLeft: '1.5em', marginTop: '5em' }}>
                <h2 style={{ fontSize: '1.8em', margin: 0 }}>3. Performance Benchmarks</h2>
                <p style={{ color: 'var(--text-secondary)', fontStyle: 'italic', marginTop: '0.5em' }}>Execution Time Comparison on NVIDIA T4 GPU</p>
            </div>

            <section className="section" style={{ marginTop: '2em' }}>
                <p style={{ lineHeight: '1.8', marginBottom: '2em' }}>
                    The implementation was thoroughly profiled and benchmarked on a Google Colab instance using an NVIDIA T4 GPU. The table below illustrates the runtimes across different point counts:
                </p>
                
                <div style={{ overflowX: 'auto', marginBottom: '2em' }}>
                    <table style={{
                        width: '100%',
                        borderCollapse: 'collapse',
                        margin: '1em 0',
                        fontSize: '1em',
                        textAlign: 'left',
                        boxShadow: '0 4px 15px rgba(0, 0, 0, 0.05)',
                        borderRadius: '8px',
                        overflow: 'hidden',
                        border: '1px solid var(--glass-border)'
                    }}>
                        <thead>
                            <tr style={{ backgroundColor: 'var(--bg-secondary)', borderBottom: '2px solid var(--glass-border)' }}>
                                <th style={{ padding: '12px 15px', fontWeight: 'bold' }}>Point Count (N)</th>
                                <th style={{ padding: '12px 15px', fontWeight: 'bold' }}>CPU Naive O(N²)</th>
                                <th style={{ padding: '12px 15px', fontWeight: 'bold' }}>CPU Grid O(N)</th>
                                <th style={{ padding: '12px 15px', fontWeight: 'bold' }}>GPU Naive O(N²)</th>
                                <th style={{ padding: '12px 15px', fontWeight: 'bold' }}>GPU Grid DSU (O(N))</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                                <td style={{ padding: '12px 15px', fontWeight: 'bold' }}>1,000</td>
                                <td style={{ padding: '12px 15px' }}>0.00396s</td>
                                <td style={{ padding: '12px 15px' }}>0.00292s</td>
                                <td style={{ padding: '12px 15px' }}>0.31057s</td>
                                <td style={{ padding: '12px 15px', color: 'var(--accent-primary)' }}>0.20183s</td>
                            </tr>
                            <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                                <td style={{ padding: '12px 15px', fontWeight: 'bold' }}>5,000</td>
                                <td style={{ padding: '12px 15px' }}>0.09301s</td>
                                <td style={{ padding: '12px 15px' }}>0.04393s</td>
                                <td style={{ padding: '12px 15px' }}>0.17882s</td>
                                <td style={{ padding: '12px 15px', color: 'var(--accent-primary)' }}>0.17464s</td>
                            </tr>
                            <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                                <td style={{ padding: '12px 15px', fontWeight: 'bold' }}>10,000</td>
                                <td style={{ padding: '12px 15px' }}>0.37067s</td>
                                <td style={{ padding: '12px 15px' }}>0.16974s</td>
                                <td style={{ padding: '12px 15px' }}>0.16381s</td>
                                <td style={{ padding: '12px 15px', color: 'var(--accent-primary)' }}>0.16294s</td>
                            </tr>
                            <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                                <td style={{ padding: '12px 15px', fontWeight: 'bold' }}>20,000</td>
                                <td style={{ padding: '12px 15px' }}>1.47097s</td>
                                <td style={{ padding: '12px 15px' }}>0.67796s</td>
                                <td style={{ padding: '12px 15px' }}>0.35339s</td>
                                <td style={{ padding: '12px 15px', color: 'var(--accent-primary)' }}>0.24352s</td>
                            </tr>
                            <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                                <td style={{ padding: '12px 15px', fontWeight: 'bold' }}>50,000</td>
                                <td style={{ padding: '12px 15px', color: 'var(--text-secondary)' }}>N/A (Too slow)</td>
                                <td style={{ padding: '12px 15px' }}>4.41346s</td>
                                <td style={{ padding: '12px 15px', color: 'var(--text-secondary)' }}>N/A</td>
                                <td style={{ padding: '12px 15px', color: 'var(--accent-primary)' }}>0.51060s</td>
                            </tr>
                            <tr style={{ borderBottom: '1px solid var(--glass-border)' }}>
                                <td style={{ padding: '12px 15px', fontWeight: 'bold' }}>100,000</td>
                                <td style={{ padding: '12px 15px', color: 'var(--text-secondary)' }}>N/A (Too slow)</td>
                                <td style={{ padding: '12px 15px' }}>18.30190s</td>
                                <td style={{ padding: '12px 15px', color: 'var(--text-secondary)' }}>N/A</td>
                                <td style={{ padding: '12px 15px', color: 'var(--accent-primary)', fontWeight: 'bold' }}>1.01834s</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                {/* Visual Chart Section */}
                <div className="glass-panel" style={{
                    padding: '2em',
                    borderRadius: '12px',
                    border: '1px solid var(--glass-border)',
                    background: 'var(--glass-bg)',
                    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
                    marginBottom: '3em',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center'
                }}>
                    <h3 style={{ fontSize: '1.1em', marginBottom: '1.5em', fontWeight: '400', alignSelf: 'flex-start', fontFamily: 'var(--font-heading)' }}>Execution Time vs. Point Count (Log-10 Scale)</h3>
                    
                    <svg viewBox="0 0 720 300" style={{ width: '100%', height: 'auto', overflow: 'visible' }}>
                        {/* Definitions for Gradients */}
                        <defs>
                            <linearGradient id="gpuGridGradient" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="0%" stopColor="#49bf9c" stopOpacity="0.25" />
                                <stop offset="100%" stopColor="#49bf9c" stopOpacity="0.0" />
                            </linearGradient>
                        </defs>

                        {/* Y-Axis Gridlines & Labels */}
                        {/* 10s */}
                        <line x1="60" y1="54" x2="520" y2="54" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="4 4" />
                        <text x="50" y="58" textAnchor="end" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">10 s</text>

                        {/* 1s */}
                        <line x1="60" y1="100" x2="520" y2="100" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="4 4" />
                        <text x="50" y="104" textAnchor="end" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">1 s</text>

                        {/* 100ms */}
                        <line x1="60" y1="147" x2="520" y2="147" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="4 4" />
                        <text x="50" y="151" textAnchor="end" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">100 ms</text>

                        {/* 10ms */}
                        <line x1="60" y1="193" x2="520" y2="193" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="4 4" />
                        <text x="50" y="197" textAnchor="end" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">10 ms</text>

                        {/* 1ms */}
                        <line x1="60" y1="240" x2="520" y2="240" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="4 4" />
                        <text x="50" y="244" textAnchor="end" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">1 ms</text>

                        {/* X-Axis Gridlines & Labels */}
                        {/* 1k */}
                        <line x1="60" y1="40" x2="60" y2="240" stroke="var(--glass-border)" strokeWidth="1" />
                        <text x="60" y="260" textAnchor="middle" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">1k</text>

                        {/* 5k */}
                        <line x1="152" y1="40" x2="152" y2="240" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="2 2" />
                        <text x="152" y="260" textAnchor="middle" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">5k</text>

                        {/* 10k */}
                        <line x1="244" y1="40" x2="244" y2="240" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="2 2" />
                        <text x="244" y="260" textAnchor="middle" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)" fontWeight="bold">10k</text>

                        {/* 20k */}
                        <line x1="336" y1="40" x2="336" y2="240" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="2 2" />
                        <text x="336" y="260" textAnchor="middle" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">20k</text>

                        {/* 50k */}
                        <line x1="428" y1="40" x2="428" y2="240" stroke="var(--glass-border)" strokeWidth="1" strokeDasharray="2 2" />
                        <text x="428" y="260" textAnchor="middle" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">50k</text>

                        {/* 100k */}
                        <line x1="520" y1="40" x2="520" y2="240" stroke="var(--glass-border)" strokeWidth="1" />
                        <text x="520" y="260" textAnchor="middle" fontSize="11" fill="var(--text-secondary)" fontFamily="var(--font-body)">100k</text>

                        {/* Chart Axes lines */}
                        <line x1="60" y1="240" x2="520" y2="240" stroke="var(--text-primary)" strokeWidth="1.5" />
                        <line x1="60" y1="40" x2="60" y2="240" stroke="var(--text-primary)" strokeWidth="1.5" />

                        {/* Gradient Fill under GPU Grid DSU line */}
                        <path d="M 60,132.8 L 152,135.7 L 244,137.1 L 336,129.0 L 428,114.1 L 520,100.1 L 520,240 L 60,240 Z" fill="url(#gpuGridGradient)" />

                        {/* Data Lines */}
                        {/* CPU Naive */}
                        <path d="M 60,212.2 L 152,148.5 L 244,120.5 L 336,92.7" fill="none" stroke="#e74c3c" strokeWidth="2.5" strokeDasharray="4 4" />
                        
                        {/* GPU Naive */}
                        <path d="M 60,124.1 L 152,135.3 L 244,137.0 L 336,121.5" fill="none" stroke="#3498db" strokeWidth="2.5" strokeDasharray="4 4" />

                        {/* CPU Grid */}
                        <path d="M 60,218.4 L 152,163.6 L 244,136.3 L 336,108.3 L 428,70.5 L 520,41.8" fill="none" stroke="#f39c12" strokeWidth="2.5" />

                        {/* GPU Grid DSU */}
                        <path d="M 60,132.8 L 152,135.7 L 244,137.1 L 336,129.0 L 428,114.1 L 520,100.1" fill="none" stroke="#49bf9c" strokeWidth="3" />

                        {/* Data Points Markers */}
                        {/* CPU Naive Markers */}
                        <circle cx="60" cy="212.2" r="4" fill="#e74c3c" />
                        <circle cx="152" cy="148.5" r="4" fill="#e74c3c" />
                        <circle cx="244" cy="120.5" r="4" fill="#e74c3c" />
                        <circle cx="336" cy="92.7" r="4" fill="#e74c3c" />

                        {/* GPU Naive Markers */}
                        <polygon points="60,120.1 56,128.1 64,128.1" fill="#3498db" />
                        <polygon points="152,131.3 148,139.3 156,139.3" fill="#3498db" />
                        <polygon points="244,133.0 240,141.0 248,141.0" fill="#3498db" />
                        <polygon points="336,117.5 332,125.5 340,125.5" fill="#3498db" />

                        {/* CPU Grid Markers */}
                        <rect x="56" y="214.4" width="8" height="8" fill="#f39c12" />
                        <rect x="148" y="159.6" width="8" height="8" fill="#f39c12" />
                        <rect x="240" y="132.3" width="8" height="8" fill="#f39c12" />
                        <rect x="332" y="104.3" width="8" height="8" fill="#f39c12" />
                        <rect x="424" y="66.5" width="8" height="8" fill="#f39c12" />
                        <rect x="516" y="37.8" width="8" height="8" fill="#f39c12" />

                        {/* GPU Grid DSU Markers */}
                        <circle cx="60" cy="132.8" r="5" fill="#49bf9c" stroke="var(--bg-primary)" strokeWidth="1.5" />
                        <circle cx="152" cy="135.7" r="5" fill="#49bf9c" stroke="var(--bg-primary)" strokeWidth="1.5" />
                        <circle cx="244" cy="137.1" r="5" fill="#49bf9c" stroke="var(--bg-primary)" strokeWidth="1.5" />
                        <circle cx="336" cy="129.0" r="5" fill="#49bf9c" stroke="var(--bg-primary)" strokeWidth="1.5" />
                        <circle cx="428" cy="114.1" r="5" fill="#49bf9c" stroke="var(--bg-primary)" strokeWidth="1.5" />
                        <circle cx="520" cy="100.1" r="5" fill="#49bf9c" stroke="var(--bg-primary)" strokeWidth="1.5" />

                        {/* Crossover Annotation Indicator */}
                        <circle cx="244" cy="137" r="10" fill="none" stroke="#f39c12" strokeWidth="1.5" strokeDasharray="2 2" />
                        <text x="256" y="152" fontSize="10" fill="#f39c12" fontWeight="bold" fontFamily="var(--font-body)">Crossover point (10k)</text>

                        {/* Chart Legend */}
                        <g transform="translate(545, 60)">
                            {/* GPU Grid DSU */}
                            <line x1="0" y1="10" x2="25" y2="10" stroke="#49bf9c" strokeWidth="3" />
                            <circle cx="12.5" cy="10" r="4" fill="#49bf9c" />
                            <text x="35" y="14" fontSize="11" fill="var(--text-primary)" fontWeight="bold" fontFamily="var(--font-body)">GPU Grid DSU</text>

                            {/* CPU Grid */}
                            <line x1="0" y1="35" x2="25" y2="35" stroke="#f39c12" strokeWidth="2" />
                            <rect x="8.5" y="31" width="8" height="8" fill="#f39c12" />
                            <text x="35" y="39" fontSize="11" fill="var(--text-primary)" fontFamily="var(--font-body)">CPU Grid</text>

                            {/* GPU Naive */}
                            <line x1="0" y1="60" x2="25" y2="60" stroke="#3498db" strokeWidth="2" strokeDasharray="3 3" />
                            <polygon points="12.5,56 8.5,64 16.5,64" fill="#3498db" />
                            <text x="35" y="64" fontSize="11" fill="var(--text-primary)" fontFamily="var(--font-body)">GPU Naive</text>

                            {/* CPU Naive */}
                            <line x1="0" y1="85" x2="25" y2="85" stroke="#e74c3c" strokeWidth="2" strokeDasharray="3 3" />
                            <circle cx="12.5" cy="85" r="3" fill="#e74c3c" />
                            <text x="35" y="89" fontSize="11" fill="var(--text-primary)" fontFamily="var(--font-body)">CPU Naive</text>
                        </g>
                    </svg>
                </div>

                <p style={{ lineHeight: '1.8' }}>
                    <strong>Key Insights:</strong>
                </p>
                <ul className="bullet-points" style={{ marginTop: '1em', lineHeight: '1.8' }}>
                    <li><strong>Parallel Scaling:</strong> At small sizes (N = 1,000), the sequential CPU implementations are faster due to the GPU kernel launch and Host-to-Device memory transfer overhead.</li>
                    <li><strong>The Break-Even Point:</strong> Around 10,000 points, the overhead cost is fully offset by hardware parallelization, and the GPU begins to outscale the CPU.</li>
                    <li><strong>18.0x Acceleration:</strong> At 100,000 points, the GPU Grid DSU implementation runs in just <b>1.018 seconds</b>, representing an 18.0x speedup over the optimized CPU Spatial Grid implementation (18.301 seconds) and orders of magnitude speedup over the naive CPU approach.</li>
                </ul>
            </section>
        </div>
    );
};

export default GPUClusteringDetails;
